### ISSUE TITLE
Script incorrectly hijacks the apt-get sources list and forces wrong ubuntu release

### ISSUE THREAD

**Issue by xavierjefferson** [dclardy64/ISPConfig-3-Debian-Installer#77]
I ran this script a few times before I finally figured out what was going on.  I was running this on 12.04 and noticed that while apt-get was running, there were several lines shown that read 'trusty' -- which is ubuntu 14.04.  It was effectively pulling updates from the wrong mirror.

The script is injecting a text file for all of the mirrors for 14.04, replacing any existing 'sources.list' file.  This is BAD, BAD practice as it assumes an install on a clean 14.04 machine.  I'd take that part of the code out unless it can be refined to use the current ubuntu version 100% of the time. 

This actually sucked doubly because I was setting up a VPS on digitalocean, and digitalocean has their own mirrors preconfigured on the VPSs for sake of speed.

**Comment by budgierless** [comment]
issue confirmed, source is not for 12.04. still needs fixing :(
