### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by KardiWeb** [dclardy64/ISPConfig-3-Debian-Installer#84]
* Starting web server apache2                                                  (98)Address already in use: AH00072: make_sock: could not bind to address [::]:80
(98)Address already in use: AH00072: make_sock: could not bind to address 0.0.0.0:80
no listening sockets available, shutting down
AH00015: Unable to open logs
Action 'start' failed.
The Apache error log may have more information.

**Comment by dclardy64** [comment]
No idea. This shouldn't be related to my script. I am following the Perfect Server script on the howtoforge website..
