### ISSUE TITLE
ISPConfig3.tgz

### ISSUE THREAD

**Issue by Alf71** [dclardy64/ISPConfig-3-Debian-Installer#85]
ISPConfig3.tgz not in gzip format

**Comment by dclardy64** [comment]
i am not sure what you are saying here.

**Comment by Alf71** [comment]
Hi,

I wasn't able to automatize the installation using Ubuntu 14.04 LTS
and I'm getting an error message "ISPConfig3.tgz not in gzip format"

**Comment by dclardy64** [comment]
No idea what this could be. This has worked forever for a lot of people.
