### ISSUE TITLE
jailkit

### ISSUE THREAD

**Issue by fnasserddine** [dclardy64/ISPConfig-3-Debian-Installer#87]
please note that for some reason jailkit block Directory listing on ftp. i am using debian 7 i removed it and everything work fine now.

**Comment by metalcated** [comment]
Can you please provide more information on specific setup? Thanks

**Comment by fnasserddine** [comment]
i just buy a debian 7 Vps and i update it & upgrade it and then i lunched
your ispconfig installer. Please tell me what other information do you need
and i will provide it to you.
please also note that i executed this command before starting the Ispconfig
installer otherwise ispconfig setup does not start :
dpkg-reconfigure dash
and then i chose no
*Thank you.*

2015-02-21 12:35 GMT+00:00 metalcated <notifications@github.com>:

**Comment by dclardy64** [comment]
The script has worked for many people for a long time. I have no idea how to reproduce what you are seeing.
