### ISSUE TITLE
Mysql server 5.6

### ISSUE THREAD

**Issue by magicbel** [dclardy64/ISPConfig-3-Debian-Installer#88]
Hello !
I tested your script but this one crash when configuring the SQL Server 5.6 :/

Config 
Debian last version 7.8.0 X64

installation sequence
Fresh install - update/upgrade - install script - 

Error : (french install) mysqldPas de répertoire, connexion avec HOME=/
Tks !

**Comment by magicbel** [comment]
Hummm -> Bad repo i think. 

cat > /etc/apt/sources.list.d/dotdeb.list <<EOF
# DotDeb
deb http://packages.dotdeb.org wheezy all
deb-src http://packages.dotdeb.org wheezy all

**Comment by dclardy64** [comment]
How much memory does your server have?

**Comment by magicbel** [comment]
Hello Dclardy !

I found the error and it's not the script but my config :-)
I am under a VM ESXi and configuration of the network card was bad .
I'll test the script again to see if now I have no problem with SQL Server..... 

I come back with news as soon :+1:

**Comment by magicbel** [comment]
The installaton works, it was actually a network card problem.
Quick question: Is what Rouncube is installed in the package or I have to install it after ISPConfig ?

For the question (french translate), 
 - mysqldPas de répertoire, connexion avec HOME=/
- Mysql no folder, connection with HOME=/

Have a nice day !

**Comment by dclardy64** [comment]
You have to install it afterwards with the extra script.

**Comment by magicbel** [comment]
Ok tks ! ;-)
