### ISSUE TITLE
how can i uninstall it?

### ISSUE THREAD

**Issue by bigf8** [dclardy64/ISPConfig-3-Debian-Installer#89]
when i install ispconfig3 in my vps,debian7,but there's a problem can not download ISPConfig-3-stable.tar.gz ,so i ask how to uninstall it?
thanks

**Comment by dclardy64** [comment]
If you installed this on a VPS that was new, it would be easier to just reformat it with your provider. Other than that, you can read through the scripts to see what is happening and do the reverse.
