### ISSUE TITLE
DKIM

### ISSUE THREAD

**Issue by chasgoj** [dclardy64/ISPConfig-3-Debian-Installer#90]
Hi,
is it possible to add setup (or separate script) for signing emails with DKIM? I installed ispconfig dkim patch and in ispconfig there is an option but emails are not signed. I'm not an expert and I'm trying few days now without success.
Thanks for everything.

**Comment by psycho-project** [comment]
Using this installer I followed clear tutorial to "install DKIM" with ease:

https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-dkim-with-postfix-on-debian-wheezy

**Comment by dclardy64** [comment]
I will look into adding this function as an addition to the roundcube install that I am doing.

**Comment by aairey** [comment]
Doesn't ISPConfig 3.1 include this natively?

**Comment by dclardy64** [comment]
It looks like it does. I will close the request. I haven't followed the development of ISPConfig very closely. I just recently started using it again for my personal sites, and I figured I would give this project a look.
