### ISSUE TITLE
Debian jessie 

### ISSUE THREAD

**Issue by lukyrys** [dclardy64/ISPConfig-3-Debian-Installer#94]
No work propertly on jessie.
After install wont work ispconfig on port 8080, some mistakes in apache configurations etc..
I must install manually 
`apt-get install apache2 apache2.2-common apache2-doc apache2-mpm-prefork apache2-utils libexpat1 ssl-cert libapache2-mod-php5 php5 php5-common php5-gd php5-mysql php5-imap phpmyadmin php5-cli php5-cgi libapache2-mod-fcgid apache2-suexec php-pear php-auth php5-mcrypt mcrypt php5-imagick imagemagick libruby libapache2-mod-python php5-curl php5-intl php5-memcache php5-memcached php5-pspell php5-recode php5-sqlite php5-tidy php5-xmlrpc php5-xsl memcached libapache2-mod-passenger`
with deleting php5-mysqlnd before (else package confilict)

**Comment by Arrakeen** [comment]
PHP/Apache versions are different on each version (wheezy/jessie), the script must be updated for the latest release of Debian.
