### ISSUE TITLE
Email forwarding not working

### ISSUE THREAD

**Issue by KardiWeb** [dclardy64/ISPConfig-3-Debian-Installer#95]
Hello dear developer!

ISPConfig email forwarding not working :(

Email replay:
Delivery to the following recipient failed permanently:

```
 example@domain.com
```

Technical details of permanent failure:
Google tried to deliver your message, but it was rejected by the server for the recipient domain domain.com by mail.domin.com. [8.8.8.8].

The error that the other server returned was:
550 5.1.1 example@domain.com: Recipient address rejected: User unknown in local recipient table

----- Original message -----

DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=gmail.com; s=20120113;
        h=mime-version:date:message-id:subject:from:to:content-type;
        bh=YN/ZTrQX0x8oxn4UQWuFEeDt8uOQj4scWJT0lxvYErU=;
        b=PyeYaLU37ghO7tnCv/B833GbCLcVio3x++NDwM2PvfIX6rhpJj6exSaYX31m0qKpyl
         zSFc6ZeCjX4NqtSAF3oIFNm2U6zRn0LUgOZ24CTS37sfQA8/GA7IhsV0G15XW15UEvRL
         S8SmMjqyWF61xpMk7/QnKMtuXGRjSmEGvhm2GoTfgfdfSl+WyiD1xrB5DdtN4BSifVQk
         RGjAJ1C7ZeJKy8GmTpp6RZ4dGoqvzBb00sUGdTdNv1BBERa/BERDTPNmCPZ0RqKa1d78
         cYxI67QWdXXuJFOk5oeaCf/UfZ/OJHvELd6KSLo6VVBJ35iFGYctrywLf6NbmW/KQyf8
         X0gA==
MIME-Version: 1.0
X-Received: by 10.194.97.196 with SMTP id ec4mr24613155wjb.3.1434097524452;
 Fri, 12 Jun 2015 01:25:24 -0700 (PDT)
Received: by 10.27.13.138 with HTTP; Fri, 12 Jun 2015 01:25:24 -0700 (PDT)
Date: Fri, 12 Jun 2015 08:25:24 +0000
Message-ID: <CAN12Ct9MwcPAAoyrpCHWn=ME5BesKi0C3SR7nYZpf=Oyu4v=CQ@mail.gmail.com>
Subject: Teszt 11
From: =?UTF-8?B?TMOhc3psw7MgS2FyZG9z?= sender.name@gmail.com
To: example@domain.com
Content-Type: multipart/alternative; boundary=047d7bf0ef1884b0f505184dd9a7

Test 11

/var/log/mail.log

Jun 12 00:00:01 s postfix/smtpd[11383]: connect from localhost[::1]
Jun 12 00:00:01 s dovecot: imap-login: Disconnected (disconnected before aut$
Jun 12 00:00:01 s dovecot: pop3-login: Disconnected (no auth attempts in 0 s$
Jun 12 00:00:01 s postfix/smtpd[11383]: lost connection after CONNECT from l$
Jun 12 00:00:01 s postfix/smtpd[11383]: disconnect from localhost[::1]
Jun 12 00:05:01 s dovecot: imap-login: Disconnected (disconnected before aut$
Jun 12 00:05:01 s postfix/smtpd[11531]: connect from localhost[::1]
Jun 12 00:05:01 s postfix/smtpd[11531]: lost connection after CONNECT from l$
Jun 12 00:05:01 s postfix/smtpd[11531]: disconnect from localhost[::1]
Jun 12 00:05:01 s dovecot: pop3-login: Disconnected (no auth attempts in 0 s$
Jun 12 00:09:01 s postfix/pickup[11011]: 89DE83E001: uid=0 from=<root>

**Comment by aairey** [comment]
This has nothing to do with this project - ISPConfig-3-Debian-**Installer**.
