### ISSUE TITLE
FEATURE REQUEST: For mailinglist, follow suit to freelists.org

### ISSUE THREAD

**Issue by zenny** [dclardy64/ISPConfig-3-Debian-Installer#97]
Hi,

The script works wonders. But for mailing list, I wish you follow suit with freelists.org (https://www.freelists.org/about.html) with:

https://www.ecartis.net/features.html
http://www.swish-e.org/
http://www.mhonarc.org/

instead of plain-old, but stable, mailman.

In their list, they have categorically stated that:

> FreeLists runs a completely free service on completely Free software. The Linux operating system, the Apache webserver, and the Ecartis mailing manager are responsible for bringing FreeLists to you daily. Mhonarc and Swish-E work in conjunction to bring you the web-based archives.

Just my two cents.

Cheers,
/z

**Comment by aairey** [comment]
First impression isn't a good one ...

My Firefox says:
```
www.ecartis.net uses an invalid security certificate. 
The certificate is not trusted because it is self-signed. (Error code: sec_error_unknown_issuer)
```

**Comment by zenny** [comment]
> www.ecartis.net uses an invalid security certificate. 
>The certificate is not trusted because it is self-signed. (Error code: sec_error_unknown_issuer)

Just a warning of the self-signed certificate, nothing serious. Maybe they prefer to use their own security certificate for more security without third-party involved, who knows?!

So not a bigger issue. If freelists.org can rely on them, other's can, too, imho.

**Comment by zenny** [comment]
UPDATE: ecartis seemed to be an abandoned project. @aairey is right. But others seems still valid.

**Comment by dclardy64** [comment]
If ISPConfig adds support for this, I can add support. 

I am not deviating from what their script provides. I believe they are using Mailman because it would be linked to domains that are hosted on the server itself.
